server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/publish?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: gdc_oa
    password: gdc_oa&pjm-!4map
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
  thymeleaf:
    encoding: utf-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging:
  file:
    name: /www/logs/demo/demo.log
  level:
    root: info
    com.example.demo.mapper: info
file:
  upload-path: /data/oa/demo/
